//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenCBS.MultiLanguageRessources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class stringRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal stringRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenCBS.MultiLanguageRessources.stringRes", typeof(stringRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please indicate the exchange rate for the date: .
        /// </summary>
        internal static string CashReceipt_NeedExchangeRate_Text {
            get {
                return ResourceManager.GetString("CashReceipt_NeedExchangeRate.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User deleted!.
        /// </summary>
        internal static string User_Delete_OK_Text {
            get {
                return ResourceManager.GetString("User_Delete_OK.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is empty!.
        /// </summary>
        internal static string User_FirstName_Empty_Text {
            get {
                return ResourceManager.GetString("User_FirstName_Empty.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is empty!.
        /// </summary>
        internal static string User_LastName_Empty_Text {
            get {
                return ResourceManager.GetString("User_LastName_Empty.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is empty!.
        /// </summary>
        internal static string User_Login_Empty_Text {
            get {
                return ResourceManager.GetString("User_Login_Empty.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is empty!.
        /// </summary>
        internal static string User_Password_Empty_Text {
            get {
                return ResourceManager.GetString("User_Password_Empty.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role is empty!.
        /// </summary>
        internal static string User_Role_Empty_Text {
            get {
                return ResourceManager.GetString("User_Role_Empty.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with same login/password already exist!.
        /// </summary>
        internal static string User_Save_AlreadyExist_Text {
            get {
                return ResourceManager.GetString("User_Save_AlreadyExist.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User saved!.
        /// </summary>
        internal static string User_Save_OK_Text {
            get {
                return ResourceManager.GetString("User_Save_OK.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User updated!.
        /// </summary>
        internal static string User_Update_OK_Text {
            get {
                return ResourceManager.GetString("User_Update_OK.Text", resourceCulture);
            }
        }
    }
}
