//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octopus.Shared.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class UserSettingsStore : global::System.Configuration.ApplicationSettingsBase {
        
        private static UserSettingsStore defaultInstance = ((UserSettingsStore)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UserSettingsStore())));
        
        public static UserSettingsStore Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en-US")]
        public string LANGUAGE {
            get {
                return ((string)(this["LANGUAGE"]));
            }
            set {
                this["LANGUAGE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BACKUP_PATH {
            get {
                return ((string)(this["BACKUP_PATH"]));
            }
            set {
                this["BACKUP_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EXPORT_PATH {
            get {
                return ((string)(this["EXPORT_PATH"]));
            }
            set {
                this["EXPORT_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AUTO_UPDATE {
            get {
                return ((bool)(this["AUTO_UPDATE"]));
            }
            set {
                this["AUTO_UPDATE"] = value;
            }
        }
    }
}
